In [13]:
import os
import numpy as np
import matplotlib.pyplot as plt

# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.image import ImageDataGenerator

2024-03-05 15:06:08.140197: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-05 15:06:08.153243: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-05 15:06:08.252037: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-05 15:06:08.252154: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-05 15:06:08.264341: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to

In [6]:
data_link = os.environ.get("LOCAL_PATH")
categories = os.listdir(data_link)
categories

['Tomato septoria leaf spot',
 'Cashew healthy',
 'Tomato leaf blight',
 'Maize leaf spot',
 'Tomato verticulium wilt',
 'Cassava healthy',
 'Maize healthy',
 'Cassava green mite',
 'Cassava brown spot',
 'Cashew red rust',
 'Tomato healthy',
 'Maize fall armyworm',
 'Cashew gumosis',
 'Maize leaf blight',
 'Cassava mosaic',
 'Cassava bacterial blight',
 'Cashew leaf miner',
 'Maize streak virus',
 'Maize grasshoper',
 'Cashew anthracnose',
 'Tomato leaf curl',
 'Maize leaf beetle']

In [38]:
sub_data = tf.keras.preprocessing.image_dataset_from_directory(
        directory="/home/mahaut/code/MahautHDL/save_the_crops/sub_data/",
        labels='inferred',
        image_size=(224,224),
        # class_names=
        label_mode="categorical",

    )
sub_data

Found 3701 files belonging to 3 classes.


<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 224, 224, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 3), dtype=tf.float32, name=None))>

In [39]:
X = []
y = []
for images, labels in sub_data.take(3701):
  X.append(images)
  y.append(labels)

In [41]:
y

[<tf.Tensor: shape=(32, 3), dtype=float32, numpy=
 array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(32, 3), dtype=float32, numpy=
 array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
  

# Model initialization

In [22]:
from tensorflow.keras import layers
from tensorflow.keras import models

def initialize_model():
    model = models.Sequential()

    ### First Convolution & MaxPooling
    model.add(layers.Conv2D(32, (4,4), input_shape=(224, 224, 3), activation='relu', padding='same'))
    model.add(layers.MaxPool2D(pool_size=(2,2)))

    ### Second Convolution & MaxPooling
    # model.add(layers.Conv2D(16, (3,3), activation='relu', padding='same'))
    # model.add(layers.MaxPool2D(pool_size=(2,2)))

    ### Flattening
    model.add(layers.Flatten())

    ### One Fully Connected layer - "Fully Connected" is equivalent to saying "Dense"
    model.add(layers.Dense(2, activation='relu'))

    ### Last layer - Classification Layer with 10 outputs corresponding to 10 digits
    model.add(layers.Dense(22, activation='softmax'))

    ### Model compilation
    model.compile(loss='categorical_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])

    return model

# fit model with earlystopping

In [ ]:
X_train_small

In [23]:
from tensorflow.keras.callbacks import EarlyStopping

model_small = initialize_model()

# es = EarlyStopping(patience = 5, verbose = 2)

# history_small = model_small.fit(X_train_small, y_train_small,
#                     validation_split = 0.3,
#                     callbacks = [es],
#                     epochs = 100,
#                     batch_size = 64)

In [24]:
model_small.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 224, 224, 32)      1568      
                                                                 
 max_pooling2d (MaxPooling2  (None, 112, 112, 32)      0         
 D)                                                              
                                                                 
 flatten_6 (Flatten)         (None, 401408)            0         
                                                                 
 dense_12 (Dense)            (None, 2)                 802818    
                                                                 
 dense_13 (Dense)            (None, 22)                66        
                                                                 
Total params: 804452 (3.07 MB)
Trainable params: 804452 (3.07 MB)
Non-trainable params: 0 (0.00 Byte)
__________________

## Plotting History

def plot_history(history, title='', axs=None, exp_name=""):
    if axs is not None:
        ax1, ax2 = axs
    else:
        f, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
    
    if len(exp_name) > 0 and exp_name[0] != '_':
        exp_name = '_' + exp_name
    ax1.plot(history.history['loss'], label = 'train' + exp_name)
    ax1.plot(history.history['val_loss'], label = 'val' + exp_name)
    ax1.set_ylim(0., 2.2)
    ax1.set_title('loss')
    ax1.legend()

    ax2.plot(history.history['accuracy'], label='train accuracy'  + exp_name)
    ax2.plot(history.history['val_accuracy'], label='val accuracy'  + exp_name)
    ax2.set_ylim(0.25, 1.)
    ax2.set_title('Accuracy')
    ax2.legend()
    return (ax1, ax2)

In [ ]:
lot_history(history_small)
plt.show()

In [ ]:
res = model_small.evaluate(X_test_small, y_test_small, verbose = 0)
res